//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decision {
    
    
    public partial class clientes {
        
        /// <summary>
        /// txtLocalizar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxTextBox txtLocalizar;
        
        /// <summary>
        /// grvClientes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridView grvClientes;
        
        /// <summary>
        /// dsClientes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Devart.Data.MySql.Web.MySqlDataSource dsClientes;
        
        /// <summary>
        /// dsCidades control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Devart.Data.MySql.Web.MySqlDataSource dsCidades;
        
        /// <summary>
        /// dsBanco control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Devart.Data.MySql.Web.MySqlDataSource dsBanco;
        
        /// <summary>
        /// dsPosto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Devart.Data.MySql.Web.MySqlDataSource dsPosto;
        
        /// <summary>
        /// dsClassifica control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Devart.Data.MySql.Web.MySqlDataSource dsClassifica;
        
        /// <summary>
        /// dsSituacao control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Devart.Data.MySql.Web.MySqlDataSource dsSituacao;
        
        /// <summary>
        /// dsProfissao control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Devart.Data.MySql.Web.MySqlDataSource dsProfissao;
        
        /// <summary>
        /// dsPromotor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Devart.Data.MySql.Web.MySqlDataSource dsPromotor;
        
        /// <summary>
        /// dsAtendente control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Devart.Data.MySql.Web.MySqlDataSource dsAtendente;
        
        /// <summary>
        /// dsTerceiro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Devart.Data.MySql.Web.MySqlDataSource dsTerceiro;
    }
}
